apiVersion: v1
kind: Service
metadata:
  name: tezos-node
  namespace: "tqtezos"
spec:
  ports:
  - port: 8733
  selector:
    app: tezos-node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tezos-node
  namespace: "tqtezos"
spec:
  selector:
    matchLabels:
      app: tezos-node
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tezos-node
    spec:
      containers:
      - image: tqtezos
        imagePullPolicy: Never
        name: tezos-node
        command: ["/bin/sh", "-c"]
        args: ["/opt/tezos/bin/tezos-node run --config-file /etc/tezos/nodeconfig.json"]
        ports:
        - containerPort: 8732
          name: tezos-net
          containerPort: 8733
          name: tezos-rpc
        volumeMounts:
        - name: config-volume
          mountPath: /etc/tezos
        - name: var-volume
          mountPath: /var/tezos
      volumes:
      - name: config-volume
        configMap:
          name: tezos-config
      - name: var-volume
        persistentVolumeClaim:
          claimName: tezos-pv-claim
