apiVersion: v1
kind: Service
metadata:
  name: tezos-rpc
  namespace: "tqtezos"
spec:
  ports:
  - port: 8732
  selector:
    app: tezos-rpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tezos-rpc
  namespace: "tqtezos"
spec:
  selector:
    matchLabels:
      app: tezos-rpc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tezos-rpc
    spec:
      containers:
      - image: tqtezos
        imagePullPolicy: Never
        name: tezos-rpc
        command: ["/bin/sh", "-c"]
        args: ["/opt/tezos/bin/tezos-node run --data-dir /var/tezos/node --rpc-addr localhost:8732 --net-addr localhost:8733 --no-bootstrap-peers --bootstrap-threshold 1"]
        ports:
        - containerPort: 8732
          name: tezos-rpc
          containerPort: 8733
          name: tezos-net
        volumeMounts:
        - name: config-volume
          mountPath: /etc/tezos
        - name: var-volume
          mountPath: /var/tezos
      volumes:
      - name: config-volume
        configMap:
          name: tezos-config
      - name: var-volume
        persistentVolumeClaim:
          claimName: tezos-pv-claim
