apiVersion: batch/v1
kind: Job
metadata:
  name: activate
  namespace: "tqtezos"
spec:
  template:
    spec:
      containers:
      - name: activate
        image: registry.gitlab.com/tezos/flextesa:d33f98de-run
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["tezos-client -A tezos-node -P 8733 -d /var/tezos/client -l --block genesis activate protocol PsCARTHAGazKbHtnKfLzQg3kms52kSRpgnDY982a9oYsSXRLQEb with fitness 25 and key genesis and parameters /etc/tezos/parameters.json && tezos-client -A tezos-node -P 8733 -d /var/tezos/client -l bake for baker0 --minimal-timestamp"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/tezos
        - name: var-volume
          mountPath: /var/tezos
      restartPolicy: Never
      volumes:
      - name: config-volume
        configMap:
          name: tezos-config
      - name: var-volume
        persistentVolumeClaim:
          claimName: tezos-pv-claim
  backoffLimit: 4
